In [4]:
import pandas as pd
df = pd.read_csv("FastagFraudDetection.csv")
df

,Transaction_ID,Timestamp,Vehicle_Type,FastagID,TollBoothID,Lane_Type,Vehicle_Dimensions,Transaction_Amount,Amount_paid,Geographical_Location,Vehicle_Speed,Vehicle_Plate_Number,Fraud_indicator
0,1,1/6/2023 11:20,Bus,FTG-001-ABC-121,A-101,Express,Large,350,120,"13.059816123454882, 77.77068662374292",65,KA11AB1234,Fraud
1,2,1/7/2023 14:55,Car,FTG-002-XYZ-451,B-102,Regular,Small,120,100,"13.059816123454882, 77.77068662374292",78,KA66CD5678,Fraud
2,3,1/8/2023 18:25,Motorcycle,NaN,D-104,Regular,Small,0,0,"13.059816123454882, 77.77068662374292",53,KA88EF9012,Not Fraud
3,4,1/9/2023 2:05,Truck,FTG-044-LMN-322,C-103,Regular,Large,350,120,"13.059816123454882, 77.77068662374292",92,KA11GH3456,Fraud
4,5,1/10/2023 6:35,Van,FTG-505-DEF-652,B-102,Express,Medium,140,100,"13.059816123454882, 77.77068662374292",60,KA44IJ6789,Fraud
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,1/1/2023 22:18,Truck,FTG-445-EDC-765,C-103,Regular,Large,330,330,"13.21331620748757, 77.55413526894684",81,KA74ST0123,Not Fraud
4996,4997,1/17/2023 13:43,Van,FTG-446-LMK-432,B-102,Express,Medium,125,125,"13.21331620748757, 77.55413526894684",64,KA38UV3456,Not Fraud
4997,4998,2/5/2023 5:08,Sedan,FTG-447-PLN-109,A-101,Regular,Medium,115,115,"13.21331620748757, 77.55413526894684",93,KA33WX6789,Not Fraud
4998,4999,2/20/2023 20:34,SUV,FTG-458-VFR-876,B-102,Express,Large,145,145,"13.21331620748757, 77.55413526894684",57,KA35YZ0123,Not Fraud
4999,5000,3/10/2023 0:59,Bus,FTG-459-WSX-543,C-103,Regular,Large,330,125,"13.21331620748757, 77.55413526894684",86,KA37AB3456,Fraud

In [ ]:
df.head()

,Transaction_ID,Timestamp,Vehicle_Type,FastagID,TollBoothID,Lane_Type,Vehicle_Dimensions,Transaction_Amount,Amount_paid,Geographical_Location,Vehicle_Speed,Vehicle_Plate_Number,Fraud_indicator
0,1,1/6/2023 11:20,Bus,FTG-001-ABC-121,A-101,Express,Large,350,120,"13.059816123454882, 77.77068662374292",65,KA11AB1234,Fraud
1,2,1/7/2023 14:55,Car,FTG-002-XYZ-451,B-102,Regular,Small,120,100,"13.059816123454882, 77.77068662374292",78,KA66CD5678,Fraud
2,3,1/8/2023 18:25,Motorcycle,NaN,D-104,Regular,Small,0,0,"13.059816123454882, 77.77068662374292",53,KA88EF9012,Not Fraud
3,4,1/9/2023 2:05,Truck,FTG-044-LMN-322,C-103,Regular,Large,350,120,"13.059816123454882, 77.77068662374292",92,KA11GH3456,Fraud
4,5,1/10/2023 6:35,Van,FTG-505-DEF-652,B-102,Express,Medium,140,100,"13.059816123454882, 77.77068662374292",60,KA44IJ6789,Fraud

In [46]:

df.count()

Transaction_ID           5000
Timestamp                5000
Vehicle_Type             5000
FastagID                 4451
TollBoothID              5000
Lane_Type                5000
Vehicle_Dimensions       5000
Transaction_Amount       5000
Amount_paid              5000
Geographical_Location    5000
Vehicle_Speed            5000
Vehicle_Plate_Number     5000
Fraud_indicator          5000
dtype: int64

In [ ]:
price = df[df.Transaction_Amount>=0]["Transaction_Amount"].value_counts()
price

Transaction_Amount
0      714
120    430
100    288
350    286
300    286
110    286
290    286
340    286
330    286
140    284
130    284
150    144
145    144
115    144
180    142
160    142
60     142
70     142
90     142
125    142
Name: count, dtype: int64

In [ ]:
df.head()

,Transaction_ID,Timestamp,Vehicle_Type,FastagID,TollBoothID,Lane_Type,Vehicle_Dimensions,Transaction_Amount,Amount_paid,Geographical_Location,Vehicle_Speed,Vehicle_Plate_Number,Fraud_indicator
0,1,1/6/2023 11:20,Bus,FTG-001-ABC-121,A-101,Express,Large,350,120,"13.059816123454882, 77.77068662374292",65,KA11AB1234,Fraud
1,2,1/7/2023 14:55,Car,FTG-002-XYZ-451,B-102,Regular,Small,120,100,"13.059816123454882, 77.77068662374292",78,KA66CD5678,Fraud
2,3,1/8/2023 18:25,Motorcycle,NaN,D-104,Regular,Small,0,0,"13.059816123454882, 77.77068662374292",53,KA88EF9012,Not Fraud
3,4,1/9/2023 2:05,Truck,FTG-044-LMN-322,C-103,Regular,Large,350,120,"13.059816123454882, 77.77068662374292",92,KA11GH3456,Fraud
4,5,1/10/2023 6:35,Van,FTG-505-DEF-652,B-102,Express,Medium,140,100,"13.059816123454882, 77.77068662374292",60,KA44IJ6789,Fraud

In [ ]:
df.tail(2)

,Transaction_ID,Timestamp,Vehicle_Type,FastagID,TollBoothID,Lane_Type,Vehicle_Dimensions,Transaction_Amount,Amount_paid,Geographical_Location,Vehicle_Speed,Vehicle_Plate_Number,Fraud_indicator
4998,4999,2/20/2023 20:34,SUV,FTG-458-VFR-876,B-102,Express,Large,145,145,"13.21331620748757, 77.55413526894684",57,KA35YZ0123,Not Fraud
4999,5000,3/10/2023 0:59,Bus,FTG-459-WSX-543,C-103,Regular,Large,330,125,"13.21331620748757, 77.55413526894684",86,KA37AB3456,Fraud

In [ ]:
s = pd.Series([10,20,30,40,50,60,70])
s.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
df.sample()

,Transaction_ID,Timestamp,Vehicle_Type,FastagID,TollBoothID,Lane_Type,Vehicle_Dimensions,Transaction_Amount,Amount_paid,Geographical_Location,Vehicle_Speed,Vehicle_Plate_Number,Fraud_indicator
3410,3411,10/3/2023 1:03,Bus,FTG-763-ZXC-321,C-103,Express,Large,290,290,"13.042660878688794, 77.47580097259879",90,KA34MK5678,Not Fraud

In [ ]:
count_Vechile = df["Vehicle_Type"].value_counts()
count_Vechile

Vehicle_Type
Bus           716
Car           714
Motorcycle    714
Truck         714
Van           714
Sedan         714
SUV           714
Name: count, dtype: int64

In [ ]:
s = df.sort_values(by="Vehicle_Type")
s

,Transaction_ID,Timestamp,Vehicle_Type,FastagID,TollBoothID,Lane_Type,Vehicle_Dimensions,Transaction_Amount,Amount_paid,Geographical_Location,Vehicle_Speed,Vehicle_Plate_Number,Fraud_indicator
0,1,1/6/2023 11:20,Bus,FTG-001-ABC-121,A-101,Express,Large,350,120,"13.059816123454882, 77.77068662374292",65,KA11AB1234,Fraud
2114,2115,12/6/2023 10:05,Bus,FTG-519-QRS-012,C-103,Express,Large,330,330,"13.21331620748757, 77.55413526894684",64,AP29OP9012,Not Fraud
2107,2108,11/29/2023 16:35,Bus,FTG-888-VWX-901,C-103,Regular,Large,330,330,"13.21331620748757, 77.55413526894684",77,MH26AB1234,Not Fraud
2100,2101,12/21/2023 8:00,Bus,FTG-257-BCA-890,C-103,Express,Large,330,330,"13.21331620748757, 77.55413526894684",61,GA24MN5678,Not Fraud
2093,2094,12/14/2023 12:25,Bus,FTG-626-FGH-789,C-103,Regular,Large,330,330,"13.21331620748757, 77.55413526894684",94,AP22YZ9012,Not Fraud
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013,2014,8/21/2023 4:35,Van,FTG-482-VWX-456,B-102,Regular,Medium,125,125,"13.21331620748757, 77.55413526894684",93,KA90VW8901,Not Fraud
4457,4458,12/3/2023 23:13,Van,FTG-447-XCV-101,B-102,Regular,Medium,120,120,"12.936687032945434, 77.53113977439017",91,TN23OP0123,Not Fraud
3190,3191,3/20/2023 16:23,Van,FTG-813-POI-371,B-102,Express,Medium,110,110,"13.042660878688794, 77.47580097259879",44,KL56IJ6789,Not Fraud
417,418,2/13/2023 4:05,Van,FTG-418-UYT-863,B-102,Regular,Medium,140,90,"13.059816123454882, 77.77068662374292",94,KA16AB0123,Fraud
2812,2813,5/28/2023 5:43,Van,FTG-084-KJH-876,B-102,Express,Medium,140,140,"13.059816123454882, 77.77068662374292",58,KA44DE4567,Not Fraud

In [ ]:
s = df.sort_values(by="Lane_Type")
s

,Transaction_ID,Timestamp,Vehicle_Type,FastagID,TollBoothID,Lane_Type,Vehicle_Dimensions,Transaction_Amount,Amount_paid,Geographical_Location,Vehicle_Speed,Vehicle_Plate_Number,Fraud_indicator
0,1,1/6/2023 11:20,Bus,FTG-001-ABC-121,A-101,Express,Large,350,120,"13.059816123454882, 77.77068662374292",65,KA11AB1234,Fraud
1908,1909,5/6/2023 16:35,Van,FTG-208-GHI-678,B-102,Express,Medium,120,120,"12.936687032945434, 77.53113977439017",56,KA32OP0123,Not Fraud
3906,3907,6/26/2023 13:08,SUV,FTG-843-QWE-321,B-102,Express,Large,150,130,"12.84197701525119, 77.67547528176169",52,GA23QR6789,Fraud
1910,1911,5/8/2023 7:10,SUV,FTG-674-MNO-234,B-102,Express,Large,140,140,"12.936687032945434, 77.53113977439017",45,KA22LM7890,Not Fraud
1912,1913,5/10/2023 18:50,Car,FTG-140-STU-890,A-101,Express,Small,70,70,"12.936687032945434, 77.53113977439017",48,KA65RS5678,Not Fraud
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2127,2128,11/9/2023 16:35,SUV,FTG-548-EFG-567,B-102,Regular,Large,145,125,"13.21331620748757, 77.55413526894684",94,GA33OP9012,Fraud
2129,2130,11/11/2023 5:10,Car,FTG-014-KLM-123,A-101,Regular,Small,90,90,"13.21331620748757, 77.55413526894684",89,AP34ST7890,Not Fraud
2130,2131,11/12/2023 11:00,Motorcycle,FTG-247-NOP-456,D-106,Regular,Small,0,0,"13.21331620748757, 77.55413526894684",52,GA34UV1234,Not Fraud
2085,2086,1/2/2023 9:30,SUV,FTG-762-HIJ-345,B-102,Regular,Large,145,145,"13.21331620748757, 77.55413526894684",73,GA19IJ7890,Not Fraud
4999,5000,3/10/2023 0:59,Bus,FTG-459-WSX-543,C-103,Regular,Large,330,125,"13.21331620748757, 77.55413526894684",86,KA37AB3456,Fraud

In [ ]:
s = df.sort_values(by="Vehicle_Dimensions")
s

,Transaction_ID,Timestamp,Vehicle_Type,FastagID,TollBoothID,Lane_Type,Vehicle_Dimensions,Transaction_Amount,Amount_paid,Geographical_Location,Vehicle_Speed,Vehicle_Plate_Number,Fraud_indicator
0,1,1/6/2023 11:20,Bus,FTG-001-ABC-121,A-101,Express,Large,350,120,"13.059816123454882, 77.77068662374292",65,KA11AB1234,Fraud
2653,2654,7/7/2023 1:12,SUV,FTG-144-KJH-098,B-102,Regular,Large,180,180,"13.059816123454882, 77.77068662374292",97,KA57IJ6789,Not Fraud
2654,2655,7/26/2023 16:37,Bus,FTG-145-EDC-745,C-103,Express,Large,350,350,"13.059816123454882, 77.77068662374292",47,KA58KL0123,Not Fraud
2657,2658,9/15/2023 14:53,Truck,FTG-158-VFR-866,C-103,Regular,Large,350,350,"13.059816123454882, 77.77068662374292",92,KA61QR2345,Not Fraud
2660,2661,11/7/2023 13:08,SUV,FTG-161-POU-997,B-102,Express,Large,180,120,"13.059816123454882, 77.77068662374292",61,KA63UV0123,Fraud
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,3146,2/23/2023 20:08,Car,FTG-826-PEM-432,A-101,Regular,Small,60,60,"13.042660878688794, 77.47580097259879",60,KL45CD2345,Not Fraud
3139,3140,11/13/2023 23:48,Motorcycle,NaN,D-106,Regular,Small,0,0,"13.042660878688794, 77.47580097259879",43,KA78WB8901,Not Fraud
3138,3139,10/25/2023 8:23,Car,FTG-819-FRD-513,A-101,Express,Small,60,60,"13.042660878688794, 77.47580097259879",54,KL23QR6789,Not Fraud
3167,3168,2/25/2023 22:28,Motorcycle,NaN,D-106,Regular,Small,0,0,"13.042660878688794, 77.47580097259879",49,KL78QR2345,Not Fraud
3250,3251,9/30/2023 22:40,Car,FTG-131-ZAS-967,A-101,Express,Small,60,60,"13.042660878688794, 77.47580097259879",24,GJ89WX4567,Not Fraud

In [ ]:
s = df.sort_values(by="Transaction_ID")
s

,Transaction_ID,Timestamp,Vehicle_Type,FastagID,TollBoothID,Lane_Type,Vehicle_Dimensions,Transaction_Amount,Amount_paid,Geographical_Location,Vehicle_Speed,Vehicle_Plate_Number,Fraud_indicator
0,1,1/6/2023 11:20,Bus,FTG-001-ABC-121,A-101,Express,Large,350,120,"13.059816123454882, 77.77068662374292",65,KA11AB1234,Fraud
1,2,1/7/2023 14:55,Car,FTG-002-XYZ-451,B-102,Regular,Small,120,100,"13.059816123454882, 77.77068662374292",78,KA66CD5678,Fraud
2,3,1/8/2023 18:25,Motorcycle,NaN,D-104,Regular,Small,0,0,"13.059816123454882, 77.77068662374292",53,KA88EF9012,Not Fraud
3,4,1/9/2023 2:05,Truck,FTG-044-LMN-322,C-103,Regular,Large,350,120,"13.059816123454882, 77.77068662374292",92,KA11GH3456,Fraud
4,5,1/10/2023 6:35,Van,FTG-505-DEF-652,B-102,Express,Medium,140,100,"13.059816123454882, 77.77068662374292",60,KA44IJ6789,Fraud
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,1/1/2023 22:18,Truck,FTG-445-EDC-765,C-103,Regular,Large,330,330,"13.21331620748757, 77.55413526894684",81,KA74ST0123,Not Fraud
4996,4997,1/17/2023 13:43,Van,FTG-446-LMK-432,B-102,Express,Medium,125,125,"13.21331620748757, 77.55413526894684",64,KA38UV3456,Not Fraud
4997,4998,2/5/2023 5:08,Sedan,FTG-447-PLN-109,A-101,Regular,Medium,115,115,"13.21331620748757, 77.55413526894684",93,KA33WX6789,Not Fraud
4998,4999,2/20/2023 20:34,SUV,FTG-458-VFR-876,B-102,Express,Large,145,145,"13.21331620748757, 77.55413526894684",57,KA35YZ0123,Not Fraud
4999,5000,3/10/2023 0:59,Bus,FTG-459-WSX-543,C-103,Regular,Large,330,125,"13.21331620748757, 77.55413526894684",86,KA37AB3456,Fraud

In [8]:
sort = df["Transaction_Amount"].sort_values(ascending=True)
sort

51        0
44        0
37        0
1864      0
4980      0
       ...
24      350
0       350
21      350
3       350
2997    350
Name: Transaction_Amount, Length: 5000, dtype: int64

In [12]:
count_Vehicle = df["FastagID"].value_counts().sum()
count_Vehicle

np.int64(4451)

In [20]:
speed = df[df["Vehicle_Speed"]>100].value_counts()
speed

Transaction_ID  Timestamp         Vehicle_Type  FastagID         TollBoothID  Lane_Type  Vehicle_Dimensions  Transaction_Amount  Amount_paid  Geographical_Location                  Vehicle_Speed  Vehicle_Plate_Number  Fraud_indicator
6               1/11/2023 10:00   Sedan         FTG-066-GHI-987  A-101        Regular    Medium              160                 100          13.059816123454882, 77.77068662374292  105            KA77KL0123            Fraud              1
1706            8/18/2023 7:15    Van           FTG-756-HIJ-901  B-102        Regular    Medium              120                 60           12.936687032945434, 77.53113977439017  111            KA26YZ0123            Fraud              1
1708            8/20/2023 11:45   SUV           FTG-222-NOP-567  B-102        Regular    Large               140                 140          12.936687032945434, 77.53113977439017  118            KA28CD7890            Not Fraud          1
1712            8/24/2023 21:15   Truck         FTG-154-ZAB-789  C-103        Regular    Large               300                 300          12.936687032945434, 77.53113977439017  102            KA32KL2345            Not Fraud          1
1920            5/17/2023 13:30   Car           FTG-771-NOP-901  A-101        Regular    Small               70                  70           12.936687032945434, 77.53113977439017  105            KA21GH1234            Not Fraud          1
2506            11/28/2023 11:01  Sedan         FTG-066-GHI-947  A-101        Regular    Medium              160                 160          13.059816123454882, 77.77068662374292  105            KA77OL0123            Not Fraud          1
4206            3/13/2023 22:34   Van           FTG-009-YZA-999  B-102        Regular    Medium              120                 120          12.936687032945434, 77.53113977439017  111            DL34OP2345            Not Fraud          1
4208            4/17/2023 5:25    SUV           FTG-011-EFG-111  B-102        Regular    Large               140                 60           12.936687032945434, 77.53113977439017  118            DL78ST6789            Fraud              1
4212            6/25/2023 19:06   Truck         FTG-015-QRS-555  C-103        Regular    Large               300                 300          12.936687032945434, 77.53113977439017  102            DL67AB6789            Not Fraud          1
4420            2/24/2023 12:17   Car           FTG-409-RST-533  A-101        Regular    Small               70                  0            12.936687032945434, 77.53113977439017  105            WB34QR1234            Fraud              1
Name: count, dtype: int64

In [34]:
speed = df["Vehicle_Speed"][df["Vehicle_Speed"]>20]
speed

0       65
1       78
2       53
3       92
4       60
        ..
4995    81
4996    64
4997    93
4998    57
4999    86
Name: Vehicle_Speed, Length: 4996, dtype: int64

In [ ]:
# Ba yaha pe count likhne se Har speed kitni baar aayi:wo count hoke a jayega 
speed = df["Vehicle_Speed"][df["Vehicle_Speed"]>20].value_counts().min()
# Yaha pe tumne min likha hai Ab min() speed par nahi, counts par lag raha hai.samjha na samjha gaya na bhaau 
speed

np.int64(2)

In [ ]:
#  Series Indexing 

data = pd.Series([1,2,5,32,65], index = ["a", "b", "c", "d", "e"])
data.loc[["a", "c", "e"]]

a     1
c     5
e    65
dtype: int64

In [26]:
data.iloc[0:4]

a     1
b     2
c     5
d    32
dtype: int64

In [ ]:
data.loc[["a", "c", "e"]]

In [30]:
ans = data.loc[data>25]
ans

d    32
e    65
dtype: int64

In [31]:
s1 = pd.Series([10, 20, 30], index=["a", "b", "c"])
s2 = pd.Series([1, 2, 3], index=["a", "b", "x"])   # "x" alag hai

In [32]:
print(s1+s2)

a    11.0
b    22.0
c     NaN
x     NaN
dtype: float64

In [40]:
s2.count()

np.int64(3)

In [41]:
data.count()

np.int64(5)

In [64]:
import numpy as np
s = pd.Series([0, 2, 2, np.nan,3, 3, 4])
# data = s.unique()
# data
s
count = s.value_counts()
count

2.0    2
3.0    2
0.0    1
4.0    1
Name: count, dtype: int64

In [66]:
s.isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [70]:
# s.dropna()

In [75]:
s.fillna("Kya Karu mai eska")

0                  0.0
1                  2.0
2                  2.0
3    Kya Karu mai eska
4                  3.0
5                  3.0
6                  4.0
dtype: object

In [76]:
data>20

array([False, False, False, False])