### What is an API?

> [!NOTE]
> * **API Actually DO** $\rightarrow$ Software ko aapas mein baat karata hai.
> * **Pipeline** $\rightarrow$ Jo information ko **Point A** se **Point B** tak pahunchata hai.

### Real-World Example — IRCTC & Third-Party Apps

> [!NOTE]
> **API (Application Programming Interface)** basically **software ko aapas mein communicate / baat karne ka way provide karti hai.**

---

#### 1. IRCTC & Third-Party Platforms

Maan lo:

* **IRCTC / Railway System** $\rightarrow$ Railway ticketing ka main system
* **MakeMyTrip** $\rightarrow$ Travel booking platform
* **ixigo** $\rightarrow$ Travel booking platform
* **Other authorized platforms** $\rightarrow$ Third-party applications

Ye sab **alag-alag software/platforms** hain.

Lekin jab user **MakeMyTrip** ya **ixigo** par railway ticket search karta hai, toh application ko train ka data kahin se toh lena padega.

**Question:**
> *Train ka data Railway/IRCTC system ka hai, phir MakeMyTrip ya ixigo ko ye data milta kaise hai?*

**Answer — API:**
* IRCTC/Railway system **authorized APIs/integrations** ke through required railway information third-party platforms ko provide karta hai.
* Third-party application **directly database mein jaakar data nahi uthati**.
* Instead, API ke through **request** aur **response** exchange hota hai.

---

#### 2. Request & Response Flow

Suppose user search karta hai: **"Delhi → Mumbai, 25 August"**

```mermaid
sequenceDiagram
    autonumber
    actor User as User
    participant App as MakeMyTrip / ixigo (Frontend)
    participant API as API Gateway
    participant IRCTC as Railway / IRCTC System (Backend)

    User->>App: 1. Search "Delhi → Mumbai, 25 August"
    App->>API: 2. API Request (Query train details)
    API->>IRCTC: 3. Process Request (Check Route, Timing, Seats, Fare)
    IRCTC-->>API: 4. Raw Data (Train Number, Availability, Fare)
    API-->>App: 5. API Response (Structured Data)
    App-->>User: 6. Display train details on UI
```

---

#### 3. Data Access & Security

Ye important concept hai:

> **Railway/IRCTC ka data $\neq$ MakeMyTrip ka own data.**

* Third-party application ko **authorized API access/integration** mil sakta hai.
* API ke through application ko **specific requested information** milti hai.

> [!IMPORTANT]
> Third-party application normally **IRCTC ka entire database download karke apne paas nahi rakh leti**.  
> Instead, API integration ke through **required data/services access** kiye ja sakte hain, subject to the provider's authorization, rules and technical setup.

---

#### 4. Universal System Flow

```mermaid
flowchart TD
    User["User (Client)"] -->|"1. User Request"| App["Application (Frontend)"]
    App -->|"2. API Request"| API["API (Communication Bridge)"]
    API -->|"3. Data & Business Logic"| Backend["Backend / System (Database)"]
    Backend -->|"4. Return Data"| API
    API -->|"5. API Response"| App
    App -->|"6. Show Data"| User
```

**Key Takeaways:**

> • **API** = Bridge / Medium of Communication  
> • **Backend / Database** = Data & Business Logic  
> • **Frontend** = User ko information dikhane wala part  

> [!TIP]
> **Yahi basic pattern tumhe almost har modern software architecture mein baar-baar dikhega.**

### Practical Example — TMDB API

Ab hum **TMDB (The Movie Database)** ki API ka use karke movie data apni website par fetch karenge.

---

#### 1. TMDB Overview

* **TMDB (The Movie Database)** ek platform hai jahan movies aur TV shows ka data available hai.
* Is data ko hum **TMDB API** ke through apni application mein use kar sakte hain.

---

#### 2. TMDB Endpoints

Hum Google par search karenge `TMDB API`. TMDB API documentation mein humein different **API Endpoints** milenge, jahan har endpoint ka kaam alag hota hai:

| Endpoint | Description / Kaam |
| :--- | :--- |
| **Popular Movies** | Popular movies ka data |
| **Top Rated Movies** | Top rated movies ka data |
| **Upcoming Movies** | Upcoming movies ka data |
| **Movie Search** | Kisi movie ko search karna |
| **Movie Details** | Kisi specific movie ki details |

> [!NOTE]
> **Different API endpoints ko call karne par humein different type ka data milta hai.**

---

#### 3. Example — Get Top Rated Movies

Maan lo humein **Top Rated Movies** ka data chahiye:

1. TMDB documentation mein humein **Get Top Rated** naam ka endpoint milega jiske saath ek **URL** hota hai.
2. Hum us URL par request bhejenge:

```mermaid
sequenceDiagram
    autonumber
    participant App as Our Website / App
    participant API as TMDB API
    participant Server as TMDB Server & Database

    App->>API: 1. API Request (Get Top Rated)
    API->>Server: 2. Process Request & Fetch Records
    Server-->>API: 3. Movie Data (JSON)
    API-->>App: 4. API Response
    App->>App: 5. Render Movie Cards on UI
```

3. Response mein humein movie se related information mil sakti hai, jaise:
   * **Movie Name**
   * **Movie ID**
   * **Rating**
   * **Release Date**
   * **Poster**
   * **Overview**
   * **Language**

4. Phir hum is received data ko apni website par **Movie Cards** ke form mein display kar sakte hain.

---

#### 4. Main Concept

Hum **TMDB ke database ko directly access nahi kar rahe hain.**

```mermaid
flowchart LR
    A["Client Application"] -->|"1. Request"| B["TMDB API Endpoint"]
    B -->|"2. Fetch"| C["TMDB Server"]
    C -->|"3. Data"| B
    B -->|"4. Response"| A
```

> [!IMPORTANT]
> **API basically hamari website aur TMDB ke server ke beech communication ka medium hai.**

## 🎬 TMDB API – Top Rated Movies

> [!NOTE]
> Top Rated Movies ke liye **Guest Session ID** ki zarurat nahi hai — sirf ek simple API Key kaafi hai.

-----

#### 🪜 Steps to Fetch Data

| Step | Action | Details |
|------|--------|---------|
| 1️⃣ | **Create Account** | TMDB website par free account banao |
| 2️⃣ | **Get API Key** | `Profile → Settings → API → API Key (v3)` |
| 3️⃣ | **Use Endpoint** | `/3/movie/top_rated` |
| 4️⃣ | **Create URL** | `https://api.themoviedb.org/3/movie/top_rated?api_key=YOUR_API_KEY` |
| 5️⃣ | **Run URL** | Browser ya Postman mein test karo |
| 6️⃣ | **Get Data** | JSON response ke `results` key ke andar movies ka data milega |

-----

#### 🔗 Sample Request URL  : https://api.themoviedb.org/3/movie/top_rated?api_key=YOUR_API_KEY

## 📥 JSON Response ko Read Karna

API se aane wale JSON Response ko samajhna kaafi easy hai, bas neeche diye steps follow karo:

1. **API URL** ko Browser me Run karo.
2. Aapko **JSON Response** milega.
3. JSON ko achi tarah samajhne ke liye **JSON Formatter / JSON Viewer** tool use karo.
4. API ka **JSON Response copy** karo.
5. Usse **JSON Formatter** me **paste** karo.
6. **Format / Beautify** button par click karo.
7. Ab JSON properly **structured form** me dikhega.
8. `results` key ke andar aapko **Movies ka actual data** milega.

---
✅ **Note:** Isse aapka JSON data readable aur clean structure me convert ho jaayega, jisse further processing (jaise data extract karna) easy ho jaata hai.

## 🎬 TMDB Data → DataFrame

### 📌 Steps:

1. **API se JSON data lo.**
2. JSON ko **Formatter/Viewer** se readable banao.
3. `results` key se **Movies ka data** extract karo.
4. Movies ka **DataFrame (DF)** banao.
5. DF me ye **columns** rakho:
   - `ID`
   - `Title`
   - `Release Date`
   - `Overview`
   - `Popularity`
   - `Vote Average`
   - `Vote Count`
6. DF ka **Shape** check karo.
7. Shape se pata chalega:
   - **Rows → Movies Count**
   - **Columns → 7**
8. Final **DataFrame ko display** karo.

### ⬇️  Start Coding Part

In [33]:
import numpy as np
import pandas as pd
import requests

## 📡 Requests Library

### ❓ `requests` kyu use karte hain?

`requests` Python ki library hai jo **API se data lene ya bhejne** ke kaam aati hai.

---

### 🧪 Basic Example

```python
import requests

response = requests.get(url)
```

| Term | Matlab |
|------|--------|
| `requests` | API se baat karne ka tool |
| `get()` | API se data maangta hai |
| `url` | API ka address |
| `response` | API se mila data |

---

### 📥 JSON data lene ke liye:

```python
data = response.json()
```

---

### 🔄 Flow

***Python → requests.get() → TMDB API → JSON Data → DataFrame***


**Main purpose:** Python se API ko request bhejna aur API se response/data lena.

In [34]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=9c3510b4224a5c362c701d95238b950d&language=en-US&page=1")

### ⬆️Theory – API Request using Requests behind the Ho Kya Raha hai 

Jab hum ye code run karte hain:

```python
request = requests.get("API_URL")
```

Python **`requests` library** ka use karke API par ek **HTTP GET Request** bhejta hai.

API hamari request ko process karke **response me data** bhejti hai.

Jo data API se aata hai, woh `request` variable me store ho jata hai.

**Simple Flow:**

`Python → requests library → HTTP GET Request → TMDB API → Response/Data → request variable`

In [35]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
   'genre_ids': [16, 28, 12, 14],
   'id': 980431,
   'title': 'Avatar Aang: The Last Airbender',
   'original_language': 'en',
   'original_title': 'Avatar Aang: The Last Airbender',
   'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
   'popularity': 94.3399,
   'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
   'release_date': '2026-07-24',
   'softcore': False,
   'video': False,
   'vote_average': 9.2,
   'vote_count': 968},
  {'adult': False,
   'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
   'genre_ids': [35, 10749],
   'id': 1632181,
   'title': 'Accidental Partners',
   'original_language': 'es',
   'original_title': 'Socias por accidente',
   'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
   'popularity': 23.531,
   'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
   'release_date': '2026-03-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.884,
   'vote_count': 363},
  {'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 42.8084,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.876,
   'vote_count': 2129},
  {'adult': False,
   'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
   'genre_ids': [16, 28, 14],
   'id': 1311031,
   'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
   'original_language': 'ja',
   'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
   'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
   'popularity': 86.622,
   'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
   'release_date': '2025-07-18',
   'softcore': False,
   'video': False,
   'vote_average': 8.759,
   'vote_count': 1966},
  {'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 80.6492,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.728,
   'vote_count': 31131},
  {'adult': False,
   'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 54.3152,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.686,
   'vote_count': 23419},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 76.8905,
   'poster_path': '/2AvgnCwCakNiJqWZqaQhdGjWNey.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.663,
   'vote_count': 4162},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 110.5217,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.647,
   'vote_count': 7328},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 29.526,
   'poster_path': '/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.573,
   'vote_count': 14229},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 26.9491,
   'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.57,
   'vote_count': 10277},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 29.2784,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.569,
   'vote_count': 17794},
  {'adult': False,
   'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
   'genre_ids': [18, 10749],
   'id': 1232449,
   'title': 'Young Hearts',
   'original_language': 'nl',
   'original_title': 'Young Hearts',
   'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
   'popularity': 13.6799,
   'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
   'release_date': '2024-10-26',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 306},
  {'adult': False,
   'backdrop_path': '/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 53.0619,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 36501},
  {'adult': False,
   'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 30.5874,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 18764},
  {'adult': False,
   'backdrop_path': '/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg',
   'genre_ids': [16, 28, 10749, 14],
   'id': 1218925,
   'title': 'Chainsaw Man - The Movie: Reze Arc',
   'original_language': 'ja',
   'original_title': '劇場版 チェンソーマン レゼ篇',
   'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
   'popularity': 29.1966,
   'poster_path': '/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
   'release_date': '2025-09-19',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 1136},
  {'adult': False,
   'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 35.2354,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.505,
   'vote_count': 19675},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 38.7213,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 27176},
  {'adult': False,
   'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'title': 'Dilwale Dulhania Le Jayenge',
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 10.8347,
   'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
   'release_date': '1995-10-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.504,
   'vote_count': 4615},
  {'adult': False,
   'backdrop_path': '/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'title': 'Parasite',
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 39.9089,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'softcore': False,
   'video': False,
   'vote_average': 8.49,
   'vote_count': 21166},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'title': 'Your Name.',
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 27.9659,
   'poster_path': '/vfJFJPepRKapMd5G2ro7klIRysq.jpg',
   'release_date': '2016-07-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.485,
   'vote_count': 12903}],
 'total_pages': 558,
 'total_results': 11154}

# `response.json()`

`response.json()` API se aaye **JSON response ko Python ke data format** (mainly dictionary/list) me convert karta hai.

```python
data = response.json()
```

**Simple Flow:**

`API → JSON Response → response.json() → Python Dictionary/List`

In [36]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
  'genre_ids': [16, 28, 12, 14],
  'id': 980431,
  'title': 'Avatar Aang: The Last Airbender',
  'original_language': 'en',
  'original_title': 'Avatar Aang: The Last Airbender',
  'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
  'popularity': 94.3399,
  'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
  'release_date': '2026-07-24',
  'softcore': False,
  'video': False,
  'vote_average': 9.2,
  'vote_count': 968},
 {'adult': False,
  'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
  'genre_ids': [35, 10749],
  'id': 1632181,
  'title': 'Accidental Partners',
  'original_language': 'es',
  'original_title': 'Socias por accidente',
  'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
  'popularity': 23.531,
  'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
  'release_date': '2026-03-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.884,
  'vote_count': 363},
 {'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 42.8084,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.876,
  'vote_count': 2129},
 {'adult': False,
  'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
  'genre_ids': [16, 28, 14],
  'id': 1311031,
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'original_language': 'ja',
  'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'popularity': 86.622,
  'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'release_date': '2025-07-18',
  'softcore': False,
  'video': False,
  'vote_average': 8.759,
  'vote_count': 1966},
 {'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 80.6492,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.728,
  'vote_count': 31131},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 54.3152,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.686,
  'vote_count': 23419},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 76.8905,
  'poster_path': '/2AvgnCwCakNiJqWZqaQhdGjWNey.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.663,
  'vote_count': 4162},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 110.5217,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.647,
  'vote_count': 7328},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 29.526,
  'poster_path': '/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.573,
  'vote_count': 14229},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 26.9491,
  'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.57,
  'vote_count': 10277},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 29.2784,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.569,
  'vote_count': 17794},
 {'adult': False,
  'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
  'genre_ids': [18, 10749],
  'id': 1232449,
  'title': 'Young Hearts',
  'original_language': 'nl',
  'original_title': 'Young Hearts',
  'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
  'popularity': 13.6799,
  'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
  'release_date': '2024-10-26',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 306},
 {'adult': False,
  'backdrop_path': '/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 53.0619,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 36501},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 30.5874,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 18764},
 {'adult': False,
  'backdrop_path': '/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg',
  'genre_ids': [16, 28, 10749, 14],
  'id': 1218925,
  'title': 'Chainsaw Man - The Movie: Reze Arc',
  'original_language': 'ja',
  'original_title': '劇場版 チェンソーマン レゼ篇',
  'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
  'popularity': 29.1966,
  'poster_path': '/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
  'release_date': '2025-09-19',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 1136},
 {'adult': False,
  'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 35.2354,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.505,
  'vote_count': 19675},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 38.7213,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 27176},
 {'adult': False,
  'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 10.8347,
  'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.504,
  'vote_count': 4615},
 {'adult': False,
  'backdrop_path': '/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 39.9089,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.49,
  'vote_count': 21166},
 {'adult': False,
  'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'title': 'Your Name.',
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 27.9659,
  'poster_path': '/vfJFJPepRKapMd5G2ro7klIRysq.jpg',
  'release_date': '2016-07-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.485,
  'vote_count': 12903}]

## ⬆️ JSON se Required Data Extract Karna

API se jo JSON data mila hai, woh Python me convert hone ke baad ek **Dictionary** hota hai.

Ab hame poora dictionary nahi chahiye. Hame sirf **`results` key** ke andar rakhi hui Movies ki list chahiye.

### Code:

```python
data = response.json()

movies = data["results"]
```

### Yahan kya ho raha hai?

* `data` → API ka poora JSON data
* `data["results"]` → `results` key ke andar ka data
* `movies` → ab isme **saari movies ki list** hai

### Simple Flow:

**API JSON → Dictionary → `results` → Movies List → DataFrame**

Ab isi `movies` list ko hum **Pandas DataFrame** me convert karenge.

## ➡️ Movies List → DataFrame- ye Hamra last step hai

`results` se Movies ki **list** mil gayi.

Ab list ko DataFrame me convert karenge:

```python
df = pd.DataFrame(movies)
```

* `movies` → Movies ki list
* `pd.DataFrame()` → List ko DataFrame me convert karega
* `df` → Final DataFrame

**Flow:** `API → JSON → results → Movies List → DataFrame` ✅

In [37]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture ...",94.3399,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.200,968
1,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by the same man (who also got them pregnant). They for...,23.5310,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.884,363
2,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magicall...",42.8084,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.876,2129
3,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,"The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashir...",86.6220,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False,False,8.759,1966
4,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,"Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy ...",80.6492,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.728,31131
5,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime fa...",54.3152,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.686,23419
6,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most influential artists the world has ever known, and ...",76.8905,/2AvgnCwCakNiJqWZqaQhdGjWNey.jpg,2026-04-22,False,False,8.663,4162
7,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection ...,110.5217,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.647,7328
8,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,"In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily an...",29.5260,/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg,1974-12-20,False,False,8.573,14229
9,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,12 Angry Men,en,12 Angry Men,The defense and the prosecution have rested and the jury is filing into the jury room to decide ...,26.9491,/ppd84D2i9W8jXmsyInGyihiSyqz.jpg,1957-04-10,False,False,8.570,10277
10,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,Schindler's List,en,Schindler's List,The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Na...,29.2784,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,False,False,8.569,17794
11,False,/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg,"[18, 10749]",1232449,Young Hearts,nl,Young Hearts,14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neig...,13.6799,/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg,2024-10-26,False,False,8.600,306
12,False,/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg,"[28, 80, 53]",155,The Dark Knight,en,The Dark Knight,Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attor...,53.0619,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,False,False,8.500,36501
13,False,/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg,"[16, 10751, 14]",129,Spirited Away,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents under...",30.5874,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,False,False,8.500,18764
14,False,/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg,"[16, 28, 10749, 14]",1218925,Chainsaw Man - The Movie: Reze Arc,ja,劇場版 チェンソーマン レゼ篇,"In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has st...",29.1966,/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg,2025-09-19,False,False,8.500,1136
15,False,/amZavErrjrdgDwhsIdpWxHNenIx.jpg,"[14, 18, 80]",497,The Green Mile,en,The Green Mile,"A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey posses...",35.2354,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,False,False,8.505,19675
16,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,The Lord of the Rings: The Return of the King,en,The Lord of the Rings: The Return of the King,"As armies mass for a final battle that will decide the fate of the world--and powerful, ancient ...",38.7213,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,False,False,8.500,27176
17,False,/84beTJf26mfhoasUlKSOiNSutyS.jpg,"[35, 18, 10749]",19404,Dilwale Dulhania Le Jayenge,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudha...",10.8347,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,False,False,8.504,4615
18,False,/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg,"[35, 53, 18]",496243,Parasite,ko,기생충,"All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for ...",39.9089,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,False,False,8.490,21166
19,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,Your Name.,ja,君の名は。,"High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, the...",27.9659,/vfJFJPepRKapMd5G2ro7klIRysq.jpg,2016-07-01,False,False,8.485,12903

### ⬆️ JSON → DataFrame

```python
df = pd.DataFrame(response.json()['results'])
```

### Isme kya ho raha hai?

* `response.json()` → API ke JSON response ko **Python Dictionary** me convert karta hai.
* `['results']` → Dictionary ke andar se **`results` key** ka data nikalta hai.
* `results` → Isme **movies ki list** hoti hai.
* `pd.DataFrame()` → Movies ki list ko **DataFrame** me convert karta hai.

**Flow:** `JSON → results (Movies List) → DataFrame` ✅

➡️⬇️  Ab main DataFrame me se apne kaam ke **required columns** select karunga aur ek clean, useful DataFrame bana lunga.

**Required Columns:**
`ID, Title, Release Date, Overview, Popularity, Vote Average, Vote Count`

Isse hamara final DataFrame **7 useful columns** ke saath ready ho jayega. ✅

In [38]:
pd.DataFrame(response.json()['results']).head(10)[["id", "title", "release_date", "overview", "popularity", "vote_average", "vote_count"]]

,id,title,release_date,overview,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,2026-07-24,"Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture ...",94.3399,9.200,968
1,1632181,Accidental Partners,2026-03-12,Two women discover they were both scammed by the same man (who also got them pregnant). They for...,23.5310,8.884,363
2,1007757,Swapped,2026-05-01,"A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magicall...",42.8084,8.876,2129
3,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,"The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashir...",86.6220,8.759,1966
4,278,The Shawshank Redemption,1994-09-23,"Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy ...",80.6492,8.728,31131
5,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime fa...",54.3152,8.686,23419
6,936075,Michael,2026-04-22,"The story of Michael Jackson, one of the most influential artists the world has ever known, and ...",76.8905,8.663,4162
7,687163,Project Hail Mary,2026-03-15,Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection ...,110.5217,8.647,7328
8,240,The Godfather Part II,1974-12-20,"In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily an...",29.5260,8.573,14229
9,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested and the jury is filing into the jury room to decide ...,26.9491,8.570,10277

# Loop se DataFrame Banana

Ab hum **loop** ka use karenge.

Har page se movies ka data lenge, required columns select karenge aur ek **DataFrame me append** karte jayenge.

Loop khatam hone ke baad hamare paas ek **single final DataFrame** hoga, jisme approximately **11,154 movies ka data** hoga. 🎬

In [42]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated"

params = {
    "api_key": "9c3510b4224a5c362c701d95238b950d"
}

response = requests.get(url, params=params)

print(response.status_code)
print(response.text)

200
{"page":1,"results":[{"adult":false,"backdrop_path":"/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg","genre_ids":[16,28,12,14],"id":980431,"title":"Avatar Aang: The Last Airbender","original_language":"en","original_title":"Avatar Aang: The Last Airbender","overview":"Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.","popularity":94.3399,"poster_path":"/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg","release_date":"2026-07-24","softcore":false,"video":false,"vote_average":9.2,"vote_count":968},{"adult":false,"backdrop_path":"/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg","genre_ids":[35,10749],"id":1632181,"title":"Accidental Partners","original_language":"es","original_title":"Socias por accidente","overview":"Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.","popularity":23.531,"poster_path":"/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg","release_date":"2026-03-12","softcore":false,"video":false,"vote_average":8.884,"vote_count":363},{"adult":false,"backdrop_path":"/zMwhWailP1WY7sb6AoE6b8ugoy.jpg","genre_ids":[12,16,10751,14],"id":1007757,"title":"Swapped","original_language":"en","original_title":"Swapped","overview":"A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.","popularity":42.8084,"poster_path":"/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg","release_date":"2026-05-01","softcore":false,"video":false,"vote_average":8.876,"vote_count":2129},{"adult":false,"backdrop_path":"/1RgPyOhN4DRs225BGTlHJqCudII.jpg","genre_ids":[16,28,14],"id":1311031,"title":"Demon Slayer: Kimetsu no Yaiba Infinity Castle","original_language":"ja","original_title":"劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来","overview":"The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.","popularity":86.622,"poster_path":"/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg","release_date":"2025-07-18","softcore":false,"video":false,"vote_average":8.759,"vote_count":1966},{"adult":false,"backdrop_path":"/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg","genre_ids":[18,80],"id":278,"title":"The Shawshank Redemption","original_language":"en","original_title":"The Shawshank Redemption","overview":"Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.","popularity":80.6492,"poster_path":"/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg","release_date":"1994-09-23","softcore":false,"video":false,"vote_average":8.728,"vote_count":31131},{"adult":false,"backdrop_path":"/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg","genre_ids":[18,80],"id":238,"title":"The Godfather","original_language":"en","original_title":"The Godfather","overview":"Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.","popularity":54.3152,"poster_path":"/3bhkrj58Vtu7enYsRolD1fZdja1.jpg","release_date":"1972-03-14","softcore":false,"video":false,"vote_average":8.686,"vote_count":23419},{"adult":false,"backdrop_path":"/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg","genre_ids":[10402,18],"id":936075,"title":"Michael","original_language":"en","original_title":"Michael","overview":"The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.","popularity":76.8905,"poster_path":"/2AvgnCwCakNiJqWZqaQhdGjWNey.jpg","release_date":"2026-04-22","softcore":false,"video":false,"vote_average":8.663,"vote_count":4162},{"adult":false,"backdrop_path":"/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg","genre_ids":[878,12],"id":687163,"title":"Project Hail Mary","original_language":"en","original_title":"Project Hail Mary","overview":"Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.","popularity":110.5217,"poster_path":"/yihdXomYb5kTeSivtFndMy5iDmf.jpg","release_date":"2026-03-15","softcore":false,"video":false,"vote_average":8.647,"vote_count":7328},{"adult":false,"backdrop_path":"/kGzFbGhp99zva6oZODW5atUtnqi.jpg","genre_ids":[18,80],"id":240,"title":"The Godfather Part II","original_language":"en","original_title":"The Godfather Part II","overview":"In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.","popularity":29.526,"poster_path":"/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg","release_date":"1974-12-20","softcore":false,"video":false,"vote_average":8.573,"vote_count":14229},{"adult":false,"backdrop_path":"/qqHQsStV6exghCM7zbObuYBiYxw.jpg","genre_ids":[18],"id":389,"title":"12 Angry Men","original_language":"en","original_title":"12 Angry Men","overview":"The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.","popularity":26.9491,"poster_path":"/ppd84D2i9W8jXmsyInGyihiSyqz.jpg","release_date":"1957-04-10","softcore":false,"video":false,"vote_average":8.57,"vote_count":10277},{"adult":false,"backdrop_path":"/zb6fM1CX41D9rF9hdgclu0peUmy.jpg","genre_ids":[18,36,10752],"id":424,"title":"Schindler's List","original_language":"en","original_title":"Schindler's List","overview":"The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.","popularity":29.2784,"poster_path":"/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg","release_date":"1993-12-15","softcore":false,"video":false,"vote_average":8.569,"vote_count":17794},{"adult":false,"backdrop_path":"/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg","genre_ids":[18,10749],"id":1232449,"title":"Young Hearts","original_language":"nl","original_title":"Young Hearts","overview":"14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.","popularity":13.6799,"poster_path":"/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg","release_date":"2024-10-26","softcore":false,"video":false,"vote_average":8.6,"vote_count":306},{"adult":false,"backdrop_path":"/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg","genre_ids":[28,80,53],"id":155,"title":"The Dark Knight","original_language":"en","original_title":"The Dark Knight","overview":"Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.","popularity":53.0619,"poster_path":"/qJ2tW6WMUDux911r6m7haRef0WH.jpg","release_date":"2008-07-16","softcore":false,"video":false,"vote_average":8.5,"vote_count":36501},{"adult":false,"backdrop_path":"/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg","genre_ids":[16,10751,14],"id":129,"title":"Spirited Away","original_language":"ja","original_title":"千と千尋の神隠し","overview":"A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.","popularity":30.5874,"poster_path":"/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg","release_date":"2001-07-20","softcore":false,"video":false,"vote_average":8.5,"vote_count":18764},{"adult":false,"backdrop_path":"/gqTz24ZRsCP6AKjARmEivY7m0cK.jpg","genre_ids":[16,28,10749,14],"id":1218925,"title":"Chainsaw Man - The Movie: Reze Arc","original_language":"ja","original_title":"劇場版 チェンソーマン レゼ篇","overview":"In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.","popularity":29.1966,"poster_path":"/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg","release_date":"2025-09-19","softcore":false,"video":false,"vote_average":8.5,"vote_count":1136},{"adult":false,"backdrop_path":"/amZavErrjrdgDwhsIdpWxHNenIx.jpg","genre_ids":[14,18,80],"id":497,"title":"The Green Mile","original_language":"en","original_title":"The Green Mile","overview":"A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.","popularity":35.2354,"poster_path":"/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg","release_date":"1999-12-10","softcore":false,"video":false,"vote_average":8.505,"vote_count":19675},{"adult":false,"backdrop_path":"/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg","genre_ids":[12,14,28],"id":122,"title":"The Lord of the Rings: The Return of the King","original_language":"en","original_title":"The Lord of the Rings: The Return of the King","overview":"As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​","popularity":38.7213,"poster_path":"/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg","release_date":"2003-12-17","softcore":false,"video":false,"vote_average":8.5,"vote_count":27176},{"adult":false,"backdrop_path":"/84beTJf26mfhoasUlKSOiNSutyS.jpg","genre_ids":[35,18,10749],"id":19404,"title":"Dilwale Dulhania Le Jayenge","original_language":"hi","original_title":"दिलवाले दुल्हनिया ले जायेंगे","overview":"Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.","popularity":10.8347,"poster_path":"/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg","release_date":"1995-10-20","softcore":false,"video":false,"vote_average":8.504,"vote_count":4615},{"adult":false,"backdrop_path":"/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg","genre_ids":[35,53,18],"id":496243,"title":"Parasite","original_language":"ko","original_title":"기생충","overview":"All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.","popularity":39.9089,"poster_path":"/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg","release_date":"2019-05-30","softcore":false,"video":false,"vote_average":8.49,"vote_count":21166},{"adult":false,"backdrop_path":"/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg","genre_ids":[16,10749,18],"id":372058,"title":"Your Name.","original_language":"ja","original_title":"君の名は。","overview":"High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.","popularity":27.9659,"poster_path":"/vfJFJPepRKapMd5G2ro7klIRysq.jpg","release_date":"2016-07-01","softcore":false,"video":false,"vote_average":8.485,"vote_count":12903}],"total_pages":558,"total_results":11154}

In [43]:
df = pd.DataFrame()
for i in range(1,559):
    response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=9c3510b4224a5c362c701d95238b950d&language=en-US&page={}".format(i))
    temp_df = pd.DataFrame(response.json()['results']).head(10)[["id", "title", "release_date", "overview", "popularity", "vote_average", "vote_count"]]
    # df.append(temp_df, ignore_index=True)
    df = pd.concat([df, temp_df], ignore_index=True)

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

### Step: Convert DataFrame into CSV File

Ab jab hamara complete movie data `df` DataFrame mein aa gaya hai, to ise CSV file mein convert karenge.

```python
df.to_csv("movies.csv", index=False)
```

Is code ko run karne ke baad `movies.csv` naam ki file create ho jayegi.

CSV file mein hamare DataFrame ka saara movie data store ho jayega.

`index=False` ka use isliye kiya hai taaki Pandas ka index CSV file mein extra column ke roop mein save na ho.

### CSV File Check

CSV file ko check karne ke liye:

```python
df_csv = pd.read_csv("movies.csv")
df_csv.head()
```

Ab `movies.csv` hamara final movie dataset hai.