# ***Feature Engineering: Handling Date and Time Variables***

Aisa bohot baar hoga aapke Machine Learning journey me jab aap datasets par kaam karoge aur jahan columns me **Dates**, **Times**, ya phir **dono** honge. 

Unko kaise handle karna hai, yahi hum is video me dekhne wale hain.

---

> **Note:**  
> This is a **Code Walkthrough Video**, kyunki aaj isme koi bohot zyada complex theoretical concept nahi hai, balki practical feature extraction aur manipulation par focus rahega.

____

In [42]:
import numpy as np
import pandas as pd

In [43]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [44]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

***Jitna bhi Date Related kaam honga wo Mai Ess File Se karunga***

In [45]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

***Jitna bhi Time Related kaam honga wo Mai Ess File Se karunga***

<div style="background-color: #191211; padding: 30px 20px; border-radius: 12px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 850px; margin: 20px auto; color: #ffffff; box-shadow: 0 4px 15px rgba(0,0,0,0.5); text-align: center;">

<div style="font-size: 14px; text-transform: uppercase; letter-spacing: 1.5px; color: #94a3b8; margin-bottom: 6px;">Feature Extraction from Date</div>

<div style="display: inline-block; border: 2px solid #38bdf8; border-radius: 8px; padding: 10px 25px; margin-bottom: 25px; background-color: #1e293b; box-shadow: 0 0 12px rgba(56, 189, 248, 0.25);">
<div style="font-size: 30px; font-weight: bold; color: #38bdf8; text-align: left; margin-bottom: 2px; text-align:center">Date</div>
<div style="font-size: 30px; font-weight: bold; letter-spacing: 1px; color: #f8fafc; font-family: monospace;">23 Aug 2012</div>
</div>

<div style="font-size: 22px; color: #64748b; margin-bottom: 15px;">↓</div>

<table style="width: 100%; border-collapse: separate; border-spacing: 8px 0px; border: none; margin: 0 auto;">
<tr>

<td style="width: 16.6%; vertical-align: top; background-color: #18181b; border: 1.5px solid #3b82f6; border-radius: 8px; padding: 12px 6px; text-align: center;">
<div style="font-size: 14px; font-weight: bold; color: #60a5fa; margin-bottom: 6px;">Day</div>
<div style="font-size: 16px; font-weight: 700; color: #ffffff; font-family: monospace;">23</div>
</td>

<td style="width: 16.6%; vertical-align: top; background-color: #18181b; border: 1.5px solid #3b82f6; border-radius: 8px; padding: 12px 6px; text-align: center;">
<div style="font-size: 14px; font-weight: bold; color: #60a5fa; margin-bottom: 6px;">Month</div>
<div style="font-size: 16px; font-weight: 700; color: #ffffff; font-family: monospace;">8</div>
<div style="font-size: 11px; color: #94a3b8;">(August)</div>
</td>

<td style="width: 16.6%; vertical-align: top; background-color: #18181b; border: 1.5px solid #3b82f6; border-radius: 8px; padding: 12px 6px; text-align: center;">
<div style="font-size: 14px; font-weight: bold; color: #60a5fa; margin-bottom: 6px;">Year</div>
<div style="font-size: 16px; font-weight: 700; color: #ffffff; font-family: monospace;">2012</div>
</td>

<td style="width: 16.6%; vertical-align: top; background-color: #18181b; border: 1.5px solid #10b981; border-radius: 8px; padding: 12px 6px; text-align: center;">
<div style="font-size: 13px; font-weight: bold; color: #34d399; margin-bottom: 6px;">Day of Week</div>
<div style="font-size: 15px; font-weight: 700; color: #ffffff;">Thursday</div>
<div style="font-size: 11px; color: #94a3b8;">(Index: 3)</div>
</td>

<td style="width: 16.6%; vertical-align: top; background-color: #18181b; border: 1.5px solid #f59e0b; border-radius: 8px; padding: 12px 6px; text-align: center;">
<div style="font-size: 14px; font-weight: bold; color: #fbbf24; margin-bottom: 6px;">Quarter</div>
<div style="font-size: 16px; font-weight: 700; color: #ffffff; font-family: monospace;">Q3</div>
<div style="font-size: 11px; color: #94a3b8;">(Jul-Sep)</div>
</td>

<td style="width: 16.6%; vertical-align: top; background-color: #18181b; border: 1.5px solid #ec4899; border-radius: 8px; padding: 12px 6px; text-align: center;">
<div style="font-size: 14px; font-weight: bold; color: #f472b6; margin-bottom: 6px;">Semester</div>
<div style="font-size: 16px; font-weight: 700; color: #ffffff; font-family: monospace;">Sem 2</div>
<div style="font-size: 11px; color: #94a3b8;">(H2 / 2nd Half)</div>
</td>

</tr>
</table>

<div style="margin-top: 20px; font-size: 12.5px; color: #94a3b8; text-align: center;">
Ek single Date column se itne saare naye numerical aur categorical features extract kiye jaate hain.
</div>

</div>

In [46]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [47]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

### ***Sabse Pehla Aur Important Step: Convert String to Datetime***

Jab bhi aap pandas me kisi dataset ko load karte ho, toh jo `Date` ya `Time` wala column hota hai wo **by default ek Object (String)** format me load hota hai.

Agar aap usse String hi rehne doge, toh aap uske upar wo sab kuch perform nahi kar paoge (jaise Day, Month, Year, Day of Week, Quarter nikalna) jo is video me dikhaya jayega. String format par pandas ke datetime functions kaam nahi karte.

Isliye feature extraction start karne se pehle, sabse pehla kaam hota hai us string column ko **`datetime` format me convert karna**.

---

### Implementation:

```python
import pandas as pd

# String column ko datetime object me badalna
df['date'] = pd.to_datetime(df['date'])

# Ab aap asani se features extract kar sakte ho
df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

___

## ***Working with Dates***

### Convert to Datetime Datatypes

By default, dates string/object format me load hoti hain. Datetime accessor (`.dt`) ke functions use karne ke liye sabse pehle datatype ko convert karna padta hai:

In [48]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [49]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### ***1. Extract year***

In [50]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3 2019-08-17        7292       25       1
4 2019-01-06        4344       25       3

In [51]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
975 2019-11-01         888       20      14       2019
434 2019-02-15         890       13       2       2019
276 2019-11-18        5004       25      21       2019
457 2019-10-12        4347       25     195       2019
580 2018-09-29        5965       13       2       2018

### ***2- Extract Months***

In [52]:
date['date_month_number'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_number
637 2019-02-15         957       22       4       2019                  2
892 2019-12-07        1564       13      96       2019                 12
895 2018-10-31        2714       28       8       2018                 10
835 2019-04-27        2736       25       5       2019                  4
13  2018-08-24        3020       13       4       2018                  8

In [53]:
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_number,date_month_name
479,2019-10-11,5116,14,32,2019,10,October
6,2018-11-21,1282,26,1,2018,11,November
198,2018-08-28,685,25,29,2018,8,August
681,2018-09-08,6483,28,2,2018,9,September
392,2019-05-04,4508,13,1,2019,5,May

### ***3- Extract Days***

In [55]:
date['date_day'] = date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_number,date_month_name,date_day
55,2019-07-26,4976,9,1,2019,7,July,26
145,2019-04-18,351,20,2,2019,4,April,18
711,2019-07-13,6201,0,3,2019,7,July,13
68,2018-10-18,588,16,1,2018,10,October,18
624,2018-11-09,1737,1,8,2018,11,November,9

***Days of week (Matlb agr apk Pata karna hai ki Jo Days hai wo Week Ka kon Sa Din Hai Toh)***

In [ ]:
# dow = date of  week
date['date_dow'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_number,date_month_name,date_day,date_dow
236,2018-08-24,4576,22,3,2018,8,August,24,4
674,2018-08-31,4867,9,5,2018,8,August,31,4
870,2019-08-10,3800,16,2,2019,8,August,10,5
871,2018-12-26,7378,21,8,2018,12,December,26,2
183,2019-02-08,4785,14,4,2019,2,February,8,4

In [58]:
# Days of Week - Name

date['date_dow_name'] = date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_number,date_month_name,date_day,date_dow,date_dow_name
387,2019-02-02,2897,26,1,2019,2,February,2,5,Saturday
168,2019-11-16,4432,3,1,2019,11,November,16,5,Saturday
858,2019-07-13,2465,29,1,2019,7,July,13,5,Saturday
97,2018-09-27,4690,23,1,2018,9,September,27,3,Thursday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday

In [61]:
# Is Weekend
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1, 0)

date.drop(columns = ['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_number,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

### ***4- Extract week of the year***

In [63]:
date['date_week'] = date['date'].dt.week

date.drop(columns=['product_id','city_id','orders']).head()

AttributeError: 'DatetimeProperties' object has no attribute 'week'

#### `Note-` ***dt.week deprecated/removed ho chuka hai.***

In [65]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_number,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

### 5- ***Extract Quarter***

In [66]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_number,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

### ***6- Extract Semester***

In [67]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_number,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

### ***7-Extract Time elapsed between dates***

In [68]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 8, 31, 17, 47, 33, 959264)

In [69]:
today - date['date']

0     2456 days 17:47:33.959264
1     2938 days 17:47:33.959264
2     2869 days 17:47:33.959264
3     2571 days 17:47:33.959264
4     2794 days 17:47:33.959264
                 ...
995   2884 days 17:47:33.959264
996   2825 days 17:47:33.959264
997   2673 days 17:47:33.959264
998   2738 days 17:47:33.959264
999   2512 days 17:47:33.959264
Name: date, Length: 1000, dtype: timedelta64[ns]

In [70]:
(today - date['date']).dt.days

0      2456
1      2938
2      2869
3      2571
4      2794
       ...
995    2884
996    2825
997    2673
998    2738
999    2512
Name: date, Length: 1000, dtype: int64

In [74]:
# Months passed

date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12
    + (today.month - date['date'].dt.month)
)
date.head()

,date,product_id,city_id,orders,date_year,date_month_number,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2,80
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2,96
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2,94
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2,84
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1,91

In [73]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [75]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [76]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [77]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### ***1- Extract Time part***

In [78]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

#### ***Time difference***

In [79]:
today - time['date']

0     4642 days 16:57:33.959264
1     4506 days 18:07:33.959264
2     4992 days 17:26:33.959264
3     4294 days 17:16:33.959264
4     4691 days 18:36:33.959264
                 ...
995   5281 days 16:57:33.959264
996   4602 days 18:33:33.959264
997   5067 days 18:10:33.959264
998   5183 days 18:13:33.959264
999   4455 days 18:22:33.959264
Name: date, Length: 1000, dtype: timedelta64[ns]

In [80]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      4.011299e+08
1      3.893837e+08
2      4.313716e+08
3      3.710638e+08
4      4.053694e+08
           ...
995    4.563395e+08
996    3.976796e+08
997    4.378542e+08
998    4.478768e+08
999    3.849782e+08
Name: date, Length: 1000, dtype: float64

In [81]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.685498e+06
1      6.489728e+06
2      7.189527e+06
3      6.184397e+06
4      6.756157e+06
           ...
995    7.605658e+06
996    6.627994e+06
997    7.297571e+06
998    7.464614e+06
999    6.416303e+06
Name: date, Length: 1000, dtype: float64

In [82]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      111424.959433
1      108162.126100
2      119825.442766
3      103073.276100
4      112602.609433
           ...
995    126760.959433
996    110466.559433
997    121626.176100
998    124410.226100
999    106938.376100
Name: date, Length: 1000, dtype: float64